apiVersion: v1
data:
  nodekey0: '{"body":"CAESQFAE3nmTQTGOgLmn07KMT+bg7rF0gXS5u58lzBs1m7/lvOjb69L6mE80zs2PjU0sX2yt8Rz8SIv5ZGEo75DyGXs="}'
kind: ConfigMap
metadata:
  name: light0-nodekey
  namespace: default
