apiVersion: v1
data:
  priv_validator_key.json: |-
    {
      "address": "E18B0B818133AFA46A20E35CFB79D7168F913368",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "zrejuVfdcr4UIdwi4kXC3OvGfOydDPZQjQ5o3wesDcQ="
      },
      "priv_key": {
        "type": "tendermint/PrivKeyEd25519",
        "value": "TDy+kVrHW4De6q2F/O0yZpVK1FQLM7dKaS1H7s5kxKTOt6O5V91yvhQh3CLiRcLc68Z87J0M9lCNDmjfB6wNxA=="
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-10T19:25:00Z"
  name: core0-validator-key
  namespace: default
  resourceVersion: "128125"
  uid: 3cba4125-76c0-48ea-9f1a-272930121c4f
