apiVersion: apps/v1
kind: Deployment
metadata:
  name: core0
  labels:
    app: core0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: core0
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.244.69.0\"]"
    spec:
      initContainers:
        - name: set-nodekey-permissions
          image: alpine
          command: [
            "/bin/ash", "-c",
            "cp /cache/OAZHALLLMV4Q /celestia-bridge/keys/OAZHALLLMV4Q && chmod 0600 /celestia-bridge/keys/OAZHALLLMV4Q"
          ]
          volumeMounts:
            - name: bridge0-nodekey-cache
              mountPath: /cache/OAZHALLLMV4Q
              subPath: OAZHALLLMV4Q
            - name: bridge0-nodekey-volume
              mountPath: /celestia-bridge/keys/
      containers:
        - name: celestia-app
          image: jbowen93/celestia-app:multi
          args: ["start", "--p2p.persistent_peers",
                "$(CORE1)",
                "$(CORE2)",
                "$(CORE3)",
                "--rpc.laddr", "tcp://0.0.0.0:26657"
                ]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 25"]
          env:
            - name: CORE1
              valueFrom:
                configMapKeyRef:
                  name: peer-ids
                  key: peer.core1
            - name: CORE2
              valueFrom:
                configMapKeyRef:
                  name: peer-ids
                  key: peer.core2
            - name: CORE3
              valueFrom:
                configMapKeyRef:
                  name: peer-ids
                  key: peer.core3
          volumeMounts:
          - name: core0-node-key-volume
            mountPath: /celestia-app/config/node_key.json
            subPath: node_key.json
          - name: core0-validator-key-volume
            mountPath: /celestia-app/config/priv_validator_key.json
            subPath: priv_validator_key.json
          - name: genesis-volume
            mountPath: /celestia-app/config/genesis.json
            subPath: genesis.json
          - name: gentx-volume
            mountPath: /celestia-app/config/gentx
          resources: {}
        - name: celestia-node
          image: jbowen93/celestia-node:multi
          args: ["celestia", "bridge",
                 "--repo.path",
                 "/celestia-bridge",
                 "start",
                 "--core.remote",
                 "tcp://127.0.0.1:26657",
                 "--headers.trusted-hash",
                 "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7",
                 "--p2p.mutual",
                 "/ip4/192.167.10.7/tcp/2121/p2p/12D3KooWGGtejCnY3Q9XUUy6muSRm1Whgf8ijTRtwJ8DGA1164EB,/ip4/192.167.10.8/tcp/2121/p2p/12D3KooWQCbe8R4QD1jxnUs5SWWdFg5Kza3mBE94Cz1RJnLTXfNM,/ip4/192.167.10.9/tcp/2121/p2p/12D3KooWA6uovjYCgFvWhAbrcQmnLihFy1gZkdyJt8SrPKZjeWda"        
                ]
          env:
            - name: NODE_TYPE
              value: bridge
          volumeMounts:
            - name: bridge0-nodekey-volume
              mountPath: /celestia-bridge/keys/OAZHALLLMV4Q
              subPath: OAZHALLLMV4Q
          resources: {}
      restartPolicy: Always
      volumes:
      - name: gentx-volume
        configMap:
          name: gentx
      - name: genesis-volume
        configMap:
          name: genesis
          items:
            - key: golden-genesis.json
              path: genesis.json
      - name: core0-node-key-volume
        configMap:
          name: core0-node-key
          items:
            - key: node_key.json
              path: node_key.json
      - name: core0-validator-key-volume
        configMap:
          name: core0-validator-key
          items:
            - key: priv_validator_key.json
              path: priv_validator_key.json
      - name: bridge0-nodekey-cache
        configMap:
          name: bridge0-nodekey
          items:
            - key: nodekey0
              path: OAZHALLLMV4Q
      - name: bridge0-nodekey-volume
        emptyDir: {}
status: {}