version: '3'

services:
  bridge0:
    container_name: bridge0
    image: "jbowen93/celestia-node:multi"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--repo.path", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.2:26657",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7",
            "--p2p.mutual",
            "/ip4/192.167.10.7/tcp/2121/p2p/12D3KooWGGtejCnY3Q9XUUy6muSRm1Whgf8ijTRtwJ8DGA1164EB,/ip4/192.167.10.8/tcp/2121/p2p/12D3KooWQCbe8R4QD1jxnUs5SWWdFg5Kza3mBE94Cz1RJnLTXfNM,/ip4/192.167.10.9/tcp/2121/p2p/12D3KooWA6uovjYCgFvWhAbrcQmnLihFy1gZkdyJt8SrPKZjeWda"
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge0/nodekey0:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  bridge1:
    container_name: bridge1
    image: "jbowen93/celestia-node:multi"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--repo.path", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.3:26657",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7",
            "--p2p.mutual",
            "/ip4/192.167.10.6/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw,/ip4/192.167.10.8/tcp/2121/p2p/12D3KooWQCbe8R4QD1jxnUs5SWWdFg5Kza3mBE94Cz1RJnLTXfNM,/ip4/192.167.10.9/tcp/2121/p2p/12D3KooWA6uovjYCgFvWhAbrcQmnLihFy1gZkdyJt8SrPKZjeWda"
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge1/nodekey1:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  bridge2:
    container_name: bridge2
    image: "jbowen93/celestia-node:multi"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--repo.path", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.4:26657",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7",
            "--p2p.mutual",
            "/ip4/192.167.10.7/tcp/2121/p2p/12D3KooWGGtejCnY3Q9XUUy6muSRm1Whgf8ijTRtwJ8DGA1164EB,/ip4/192.167.10.6/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw,/ip4/192.167.10.9/tcp/2121/p2p/12D3KooWA6uovjYCgFvWhAbrcQmnLihFy1gZkdyJt8SrPKZjeWda"
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge2/nodekey2:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  bridge3:
    container_name: bridge3
    image: "jbowen93/celestia-node:multi"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--repo.path", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.5:26657",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7",
             "--p2p.mutual",
            "/ip4/192.167.10.6/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw,/ip4/192.167.10.8/tcp/2121/p2p/12D3KooWQCbe8R4QD1jxnUs5SWWdFg5Kza3mBE94Cz1RJnLTXfNM,/ip4/192.167.10.7/tcp/2121/p2p/12D3KooWGGtejCnY3Q9XUUy6muSRm1Whgf8ijTRtwJ8DGA1164EB"
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge3/nodekey3:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
