version: '3'

services:
  node0:
    container_name: core0
    image: "jbowen93/celestia-app:devnet"
    command: [
            "start",
            "--p2p.persistent_peers",
            "ffdc6d353abf0c53f35fbfe1106dc216121e1d17@192.167.10.3:26656",
            "9908b74112720aedabb79909fa21a2d7e59a38be@192.167.10.4:26656",
            "c4c8024a2447f08136a6a9b10515232114011ecd@192.167.10.5:26656" 
        ]
    volumes:
       - ${PWD}/celestia-app/node0/app/config/priv_validator_key.json:/celestia-app/config/priv_validator_key.json:ro
       - ${PWD}/celestia-app/node0/app/config/node_key.json:/celestia-app/config/node_key.json:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: core1
    image: "jbowen93/celestia-app:devnet"
    command: [
            "start",
            "--p2p.persistent_peers",
            "d78ad9583f27cc73738f246b93186e40cc0272e4@192.167.10.2:26656",
            "9908b74112720aedabb79909fa21a2d7e59a38be@192.167.10.4:26656",
            "c4c8024a2447f08136a6a9b10515232114011ecd@192.167.10.5:26656"
            ]
    volumes:
       - ${PWD}/celestia-app/node1/app/config/priv_validator_key.json:/celestia-app/config/priv_validator_key.json:ro
       - ${PWD}/celestia-app/node1/app/config/node_key.json:/celestia-app/config/node_key.json:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: core2
    image: "jbowen93/celestia-app:devnet"    
    command: [
            "start",
            "--p2p.persistent_peers",
            "d78ad9583f27cc73738f246b93186e40cc0272e4@192.167.10.2:26656",
            "ffdc6d353abf0c53f35fbfe1106dc216121e1d17@192.167.10.3:26656",
            "c4c8024a2447f08136a6a9b10515232114011ecd@192.167.10.5:26656"
             ]
    volumes:
       - ${PWD}/celestia-app/node2/app/config/priv_validator_key.json:/celestia-app/config/priv_validator_key.json:ro
       - ${PWD}/celestia-app/node2/app/config/node_key.json:/celestia-app/config/node_key.json:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: core3
    image: "jbowen93/celestia-app:devnet"
    command: [
            "start",
            "--p2p.persistent_peers",
            "d78ad9583f27cc73738f246b93186e40cc0272e4@192.167.10.2:26656",
            "ffdc6d353abf0c53f35fbfe1106dc216121e1d17@192.167.10.3:26656",
            "9908b74112720aedabb79909fa21a2d7e59a38be@192.167.10.4:26656",
             ]
    volumes:
       - ${PWD}/celestia-app/node3/app/config/priv_validator_key.json:/celestia-app/config/priv_validator_key.json:ro
       - ${PWD}/celestia-app/node3/app/config/node_key.json:/celestia-app/config/node_key.json:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.5

  full-node0:
    container_name: full0
    image: "jbowen93/celestia-node-full:devnet"
    command: [
            "--repo.path", "/celestia-full",
            "start",
            "--core.remote", 
            "tcp://192.167.10.2:26657",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
             ]
    volumes:
       - ${PWD}/celestia-node/full/full0/nodekey0:/celestia-full/keys/OAZHALLLMV4Q:ro
       - ${PWD}/celestia-node/full/full0/config-full0.toml:/celestia-full/config.toml:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  full-node1:
    container_name: full1
    image: "jbowen93/celestia-node-full:devnet"
    command: [
            "--repo.path", "/celestia-full",
            "start",
            "--core.remote", 
            "tcp://192.167.10.3:26657",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
             ]
    volumes:
       - ${PWD}/celestia-node/full/full1/nodekey1:/celestia-full/keys/OAZHALLLMV4Q:ro
       - ${PWD}/celestia-node/full/full1/config-full1.toml:/celestia-full/config.toml:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  full-node2:
    container_name: full2
    image: "jbowen93/celestia-node-full:devnet"
    command: [
            "--repo.path", "/celestia-full",
            "start",
            "--core.remote", 
            "tcp://192.167.10.4:26657",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
             ]
    volumes:
       - ${PWD}/celestia-node/full/full2/nodekey2:/celestia-full/keys/OAZHALLLMV4Q:ro
       - ${PWD}/celestia-node/full/full2/config-full2.toml:/celestia-full/config.toml:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  full-node3:
    container_name: full3
    image: "jbowen93/celestia-node-full:devnet"
    command: [
            "--repo.path", "/celestia-full",
            "start",
            "--core.remote", 
            "tcp://192.167.10.5:26657",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
             ]
    volumes:
       - ${PWD}/celestia-node/full/full3/nodekey3:/celestia-full/keys/OAZHALLLMV4Q:ro
       - ${PWD}/celestia-node/full/full3/config-full3.toml:/celestia-full/config.toml:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.9

  light-node0:
    container_name: light0
    image: "jbowen93/celestia-node-light:devnet"
    command: [
            "--repo.path", "/celestia-light",
            "start",
            "--headers.trusted-peer",
            "/ip4/192.167.10.6/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
             ]
    volumes:
       - ${PWD}/celestia-node/light/light0/nodekey0:/celestia-light/keys/OAZHALLLMV4Q:ro
       - ${PWD}/celestia-node/light/light0/config-light0.toml:/celestia-light/config.toml:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.10

  light-node1:
    container_name: light1
    image: "jbowen93/celestia-node-light:devnet"
    command: [
            "--repo.path", "/celestia-light",
            "start",
            "--headers.trusted-peer",
            "/ip4/192.167.10.7/tcp/2121/p2p/12D3KooWGGtejCnY3Q9XUUy6muSRm1Whgf8ijTRtwJ8DGA1164EB",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
             ]
    volumes:
       - ${PWD}/celestia-node/light/light1/nodekey1:/celestia-light/keys/OAZHALLLMV4Q:ro
       - ${PWD}/celestia-node/light/light1/config-light1.toml:/celestia-light/config.toml:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.11
        
  light-node2:
    container_name: light2
    image: "jbowen93/celestia-node-light:devnet"
    command: [
            "--repo.path", "/celestia-light",
            "start",
            "--headers.trusted-peer",
            "/ip4/192.167.10.8/tcp/2121/p2p/12D3KooWQCbe8R4QD1jxnUs5SWWdFg5Kza3mBE94Cz1RJnLTXfNM",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
             ]
    volumes:
       - ${PWD}/celestia-node/light/light2/nodekey2:/celestia-light/keys/OAZHALLLMV4Q:ro
       - ${PWD}/celestia-node/light/light2/config-light2.toml:/celestia-light/config.toml:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.12

  light-node3:
    container_name: light3
    image: "jbowen93/celestia-node-light:devnet"
    command: [
            "--repo.path", "/celestia-light",
            "start",
            "--headers.trusted-peer",
            "/ip4/192.167.10.9/tcp/2121/p2p/12D3KooWA6uovjYCgFvWhAbrcQmnLihFy1gZkdyJt8SrPKZjeWda",
            "--headers.trusted-hash", 
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
             ]
    volumes:
       - ${PWD}/celestia-node/light/light3/nodekey3:/celestia-light/keys/OAZHALLLMV4Q:ro
       - ${PWD}/celestia-node/light/light3/config-light3.toml:/celestia-light/config.toml:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.13

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
