#cloud-config
packages:
  - jq
  - moreutils

# Add users to the system.
users:
  - name: celestia
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    lock_passwd: false
    ssh_authorized_keys:
      # M1 MBA SSH Pub Key
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBwX8oGG1+ID+1ogG6ZqPNuBlqvv9GxxLXT6pcatLqr4 jskybowen@gmail.com
      # Cloud Desktop SSH Pub Key
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJncTNx1fAJiHjYe1PgLC2P3iqLqdVjt3WC4Zn8wRCov josh@celestia.org

# Set environment variables
write_files:
- path: /etc/environment
  content: |
    node_name="MightyValidator-1"
  append: true

runcmd:
  - sudo apt-get update
  - mkdir /run/tmp
  - [ wget, "https://fra1.digitaloceanspaces.com/celestia-node-binaries/celestia-appd", -O, /run/mydir/celestia-appd ]
  - [chmod, "+x", "/run/mydir/celestia-appd"]
  - [git, clone, "https://github.com/celestiaorg/networks.git" /run/mydir/.]



