[Core]
  Remote = false
  [Core.RemoteConfig]
    Protocol = ""
    RemoteAddr = ""

[P2P]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/2121", "/ip6/::/tcp/2121"]
  AnnounceAddresses = []
  NoAnnounceAddresses = ["/ip4/0.0.0.0/tcp/2121", "/ip4/127.0.0.1/tcp/2121", "/ip6/::/tcp/2121"]
  Network = "devnet"
  Bootstrapper = false
  BootstrapPeers = []
  MutualPeers = []
  PeerExchange = true 
  [P2P.ConnManager]
    Low = 50
    High = 100
    GracePeriod = 60000000000

[RPC]
  ListenAddr = ""

[Services]
  TrustedHash = ""
  TrustedPeer = ""
