apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: core3
  name: core3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: core3
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.244.69.3\"]"
    spec:
      initContainers:
        - name: set-nodekey-permissions
          image: alpine
          command: [
            "/bin/ash", "-c",
            "cp /cache/OAZHALLLMV4Q /celestia-full/keys/OAZHALLLMV4Q && chmod 0600 /celestia-full/keys/OAZHALLLMV4Q"
          ]
          volumeMounts:
            - name: full3-nodekey-cache
              mountPath: /cache/OAZHALLLMV4Q
              subPath: OAZHALLLMV4Q
            - name: full3-nodekey-volume
              mountPath: /celestia-full/keys/
      containers:
        - name: celestia-app
          image: jbowen93/celestia-app:multi
          args: ["start", "--p2p.persistent_peers",
                "$(CORE0)",
                "$(CORE1)",
                "$(CORE2)",
                "--rpc.laddr", "tcp://0.0.0.0:26657"
                ]
          ports:
          - name: rpc
            containerPort: 26657
          - name: p2p
            containerPort: 26656
          env:
            - name: CORE0
              valueFrom:
                configMapKeyRef:
                  name: peer-ids
                  key: peer.core0
            - name: CORE1
              valueFrom:
                configMapKeyRef:
                  name: peer-ids
                  key: peer.core1
            - name: CORE2
              valueFrom:
                configMapKeyRef:
                  name: peer-ids
                  key: peer.core2
          volumeMounts:
          - name: core3-node-key-volume
            mountPath: /celestia-app/config/node_key.json
            subPath: node_key.json
          - name: core3-validator-key-volume
            mountPath: /celestia-app/config/priv_validator_key.json
            subPath: priv_validator_key.json
          - name: genesis-volume
            mountPath: /celestia-app/config/genesis.json
            subPath: genesis.json
          - name: gentx-volume
            mountPath: /celestia-app/config/gentx
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 25"]
          resources: {}
        - name: celestia-node
          image: jbowen93/celestia-node:multi
          args: ["celestia", "full",
                 "--repo.path",
                 "/celestia-full",
                 "start",
                 "--core.remote",
                 "tcp://127.0.0.1:26657",
                 "--headers.trusted-hash",
                 "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7",
                 "--p2p.mutual",
                 "/ip4/192.167.10.6/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw,/ip4/192.167.10.8/tcp/2121/p2p/12D3KooWQCbe8R4QD1jxnUs5SWWdFg5Kza3mBE94Cz1RJnLTXfNM,/ip4/192.167.10.7/tcp/2121/p2p/12D3KooWGGtejCnY3Q9XUUy6muSRm1Whgf8ijTRtwJ8DGA1164EB"
                ]
          env:
            - name: NODE_TYPE
              value: full
          volumeMounts:
            - name: full3-nodekey-volume
              mountPath: /celestia-full/keys/OAZHALLLMV4Q
              subPath: OAZHALLLMV4Q
          resources: {}
      restartPolicy: Always
      volumes:
      - name: gentx-volume
        configMap:
          name: gentx
      - name: genesis-volume
        configMap:
          name: genesis
          items:
            - key: golden-genesis.json
              path: genesis.json
      - name: core3-node-key-volume
        configMap:
          name: core3-node-key
          items:
            - key: node_key.json
              path: node_key.json
      - name: core3-validator-key-volume
        configMap:
          name: core3-validator-key
          items:
            - key: priv_validator_key.json
              path: priv_validator_key.json
      - name: full3-nodekey-cache
        configMap:
          name: full3-nodekey
          items:
            - key: nodekey3
              path: OAZHALLLMV4Q
      - name: full3-nodekey-volume
status: {}







