apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seed
  name: seed
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: seed
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seed
    spec:
      containers:
      - image: jbowen93/celestia-app:seed-tired2
        imagePullPolicy: Always
        name: celestia-app
        ports:
        - containerPort: 26656
          protocol: TCP
        - containerPort: 26657
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

