apiVersion: apps/v1
kind: Deployment
metadata:
  name: light1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: light1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: light1
    spec:
      initContainers:
        - name: set-nodekey-permissions
          image: alpine
          command: [
            "/bin/ash", "-c",
            "cp /cache/OAZHALLLMV4Q /celestia-light/keys/OAZHALLLMV4Q && chmod 0600 /celestia-light/keys/OAZHALLLMV4Q"
          ]
          volumeMounts:
            - name: light1-nodekey-cache
              mountPath: /cache/OAZHALLLMV4Q
              subPath: OAZHALLLMV4Q
            - name: light1-nodekey-volume
              mountPath: /celestia-light/keys/
      containers:
        - name: light1
          image: jbowen93/celestia-node:multi
          args: [
            "celestia", "light",
            "--repo.path", "/celestia-light",
            "start",
            "--headers.trusted-peer", 
            "/ip4/10.244.69.1/tcp/2121/p2p/12D3KooWGGtejCnY3Q9XUUy6muSRm1Whgf8ijTRtwJ8DGA1164EB",
            "--headers.trusted-hash",
            "64D831D041A57A9D93078B445F7B1347024A9B5A8A444086C0B556B65A8A96C7"
          ]
          env:
            - name: NODE_TYPE
              value: light
          volumeMounts:
            - name: light1-nodekey-volume
              mountPath: /celestia-light/keys/OAZHALLLMV4Q
              subPath: OAZHALLLMV4Q
            - name: light-config-volume
              mountPath: /celestia-light/config.toml
              subPath: config.toml
          resources: {}
      restartPolicy: Always
      volumes:
      - name: light-config-volume
        configMap:
          name: light-config
          items:
            - key: config.toml
              path: config.toml
      - name: light1-nodekey-cache
        configMap:
          name: light1-nodekey
          items:
            - key: nodekey1
              path: OAZHALLLMV4Q
      - name: light1-nodekey-volume
        emptyDir: {}
status: {}
