apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-12-10T19:49:00Z"
  labels:
    app: core3
  name: core3
  namespace: default
  resourceVersion: "129396"
  uid: 86340417-e17f-4947-a415-44a1916505f1
spec:
  clusterIP: 10.96.69.3
  clusterIPs:
  - 10.96.69.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-1
    port: 26656
    protocol: TCP
    targetPort: 26656
  - name: port-2
    port: 26657
    protocol: TCP
    targetPort: 26657
  selector:
    app: core3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
