apiVersion: v1
data:
  nodekey1: |
    {"body":"CAESQBEMR7BMajb9jEsFjlcVBMcY1Oqm0clE+I5YN9+obF42X/GwcoPlT7DzKJlnVfjWSTA0ofx4AqmD+Ol26G/9SPA="}
kind: ConfigMap
metadata:
  name: bridge1-nodekey
  namespace: default
