name: docker-compose

on:
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
      - name: "Setup and Test Cluster"
        run: |
          cd devnet
          chmod 0600 celestia-node/full/*/nodekey* && chmod 0600 celestia-node/light/*/nodekey*
          ./start-docker-cluster.sh
          docker-compose -f docker/docker-compose.yml up -d
          echo "Waiting for cluster to come up"
          sleep 50
          node0=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.2:26657/block?height=1" | jq .result.block_id.hash)
          node1=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.3:26657/block?height=1" | jq .result.block_id.hash)
          node2=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.4:26657/block?height=1" | jq .result.block_id.hash)
          node3=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.5:26657/block?height=1" | jq .result.block_id.hash)
          if [ $node0 != null ] && [ $node0 = $node1 ] && [ $node0 = $node2 ] && [ $node0 = $node3 ]; then echo "$node0: success" && exit 0; else echo "failure" && exit 1; fi