name: Minikube

on:
  workflow_dispatch:

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        id: minikube
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          make docker-build
          echo -n "verifying images:"
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/hello-dep.yaml
          kubectl apply -f k8s/hello-svc.yaml
      - name: Test Service URLs
        run: |
          minikube service list
          minikube service hello --url
          echo "------------------opening the service------------------"
          curl $(minikube service hello --url)  