name: Minikube

on:
  workflow_dispatch:

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Start minikube
        id: minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --network-plugin=cni --cni=calico
      - name: Create core nodes
        run: kubectl create -f devnet/k8s/core-nodes -R
      - name: Sleep 10s
        run: sleep 10s
      - name: Test core nodes
        run: | 
          core0=$(kubectl run curl -i --restart=Never --rm -q --image=curlimages/curl:7.80.0 -- -s "http://10.244.69.0:26657/block?height=1" | jq .result.block_id.hash)
          core1=$(kubectl run curl -i --restart=Never --rm -q --image=curlimages/curl:7.80.0 -- -s "http://10.244.69.1:26657/block?height=1" | jq .result.block_id.hash)
          core2=$(kubectl run curl -i --restart=Never --rm -q --image=curlimages/curl:7.80.0 -- -s "http://10.244.69.2:26657/block?height=1" | jq .result.block_id.hash)
          core3=$(kubectl run curl -i --restart=Never --rm -q --image=curlimages/curl:7.80.0 -- -s "http://10.244.69.3:26657/block?height=1" | jq .result.block_id.hash)
          if [ $core0 != null ] && [ $core0 = $core1 ] && [ $core0 = $core2 ] && [ $core0 = $core3 ]; then echo "$core0: success" && exit 0; else echo "failure" && exit 1; fi
      - name: Create light nodes
        run: kubectl create -f devnet/k8s/light-nodes -R