
name: Semrel

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions: 
  contents: write 
  packages: write 

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Show ref v1 
        run: echo "===============> Version from $GITHUB_REF"
  # - name: Semantic Release
  #   uses: cycjimmy/semantic-release-action@v2.6.0
      