name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform -chdir=terraform/cluster init 
      - name: Terraform Plan
        id: plan
        run: terraform -chdir=terraform/cluster plan -var=do_token=${{ secrets.DIGITALOCEAN_TOKEN }} -out=tfplan
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
      - name: Terraform Apply
        id: apply
        run: terraform apply tfplan -var=do_token=${{ secrets.DIGITALOCEAN_TOKEN }}